site_name: Openveo Core
repo_url: https://github.com/veo-labs/openveo-core
theme: readthedocs
site_dir: site/version
markdown_extensions:
  - fenced_code
  - tables
pages:
- 'INTRODUCTION': 'index.md'
- 'USERS':
  - 'Prerequisites': 'prerequisites.md'
  - 'Getting started': 'getting-started.md'
  - 'Web Service': 'web-service.md'
  - 'Advanced configuration': 'advanced-configuration.md'
  - 'Scalability': 'scalability.md'
  - 'Production': 'production.md'
- 'DEVELOPERS':
  - 'The basics': 'developers/basics.md'
  - 'Prerequisites': 'developers/prerequisites.md'
  - 'Installation': 'developers/installation.md'
  - 'Write a plugin': 'developers/write-plugin.md'
  - 'Unit tests': 'developers/unit-tests.md'
  - 'End to end tests': 'developers/end-to-end-tests.md'
- 'API': 'api.md'